/** Stable public error codes — do not rename within a major version. */
export const ErrorCodes = {
  XML_PARSE: "XML_PARSE",
  JSON_PARSE: "JSON_PARSE",
  UNSUPPORTED: "UNSUPPORTED",
  IND2_ENCODING_REQUIRED: "IND2_ENCODING_REQUIRED",
  IND3_ENCODING_SHOULD_UTF8: "IND3_ENCODING_SHOULD_UTF8",
  IND5_EMPTY_ELEMENT: "IND5_EMPTY_ELEMENT",
  IND7_DUPLICATE_LANGUAGE_ID: "IND7_DUPLICATE_LANGUAGE_ID",
  IND8_MISSING_LANGUAGE_ID: "IND8_MISSING_LANGUAGE_ID",
  PROFILE_ARTIFACTS_MISSING: "PROFILE_ARTIFACTS_MISSING",
  PROFILE_SCHEMATRON: "PROFILE_SCHEMATRON",
  PROFILE_XSD: "PROFILE_XSD",
  CRYPTO_MODULE_UNAVAILABLE: "CRYPTO_MODULE_UNAVAILABLE",
  CRYPTO_NOTHING_TO_VERIFY: "CRYPTO_NOTHING_TO_VERIFY",
  CRYPTO_SKIPPED_NO_DIAN: "CRYPTO_SKIPPED_NO_DIAN",
  CUFe_MISMATCH: "CUFE_MISMATCH",
  CODELIST: "CODELIST",
} as const;
